//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//
### Einloggen in der Rolle "admin", "mitarbeiter" und "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "p") { token expiresIn roles }
}

### Neuen Film anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
      titel: "Titanic"
      genre: DRAMA,
      rating: 4,
      spieldauer: 189,
      erscheinungsjahr: 1997,
      regisseur: {
        id: 1005,
        version: 0,
        vorname: "John",
        nachname: "Doe",
        geburtsdatum: "1961-10-31"
      },
      schauspieler: [{
        id: 1000,
        version:0,
        vorname: "Jane",
        nachname: "Doe",
        geburtsdatum: "1956-07-09",
        groesse: 180
      }]
    }
  )
}

### Neues Film mit ungueltigen Daten anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
      id: 12345,
      version: 123,
      titel: "Titanic",
      genre: DRAMA,
      rating: 99,
      spieldauer: 189,
      erscheinungsjahr: 1997,
      regisseur: {
        id: 1005,
        version: 0,
        vorname: "John",
        nachname: "Doe",
        geburtsdatum: "1961-10-31"
      },
      schauspieler: [{
        id: 1000,
        version:0,
        vorname: "Jane",
        nachname: "Doe",
        geburtsdatum: "1956-07-09",
        groesse: 180
      }]
    }
  )
}

### Vorhandenes Film aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: 12345,
      titel: "Titanic 2",
    }
  )
}

### Vorhandenes Film mit ungueltigen Werten aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: abcde,
      version: defghi,
      titel: "###",
      genre: "COMEDY",
      rating: -1,
      spieldauer: 10000,
      erscheinungsjahr: 3000,
      regisseur: "nicht vorhanden",
      schauspieler: "keine"
    }
  )
}

### Nicht-Vorhandenes Film aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: 0987,
      version: 3456,
      titel: "Brooklyn",
      genre: "ROMANCE",
      rating: 97,
      spieldauer: 111,
      erscheinungsjahr: 2015,
      regisseur: "John Crowley",
      schauspieler: "Saoirse Ronan"
    }
  )
}

### Vorhandenes Film loeschen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  delete(id: "abcde")
}
