//
// N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
//

### Einloggen
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "p") {
    token
    expiresIn
    roles
  }
}

### Einloggen mit falschem Passwort
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "FALSCH") {
    token
    expiresIn
    roles
  }
}
